[tool.poetry]
name = "quinn"
version = "0.4.0"
description = "Pyspark helper methods to maximize developer efficiency"
authors = ["MrPowers <matthewkevinpowers@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/MrPowers/quinn/"
keywords = ['apachespark', 'spark', 'pyspark']

[tool.poetry.dependencies]
python = "^3.7"
cytoolz = "0.9.0.1"
pytest = "3.9.2"
pytest-cov = "2.6.0"
pyspark = "2.4.0"

[tool.poetry.dev-dependencies]
pytest = "3.9.2"
chispa = "^0.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
